from .numerology import get_numerology
from .astrology import get_astrology
from .aspects import get_aspects
from .jyotish import get_jyotish
from .karma import get_karma
from .soul_path import get_soul_path
from .destiny import get_destiny
from .psychology import get_psychology
from .childhood import get_childhood
from .ayurveda import get_ayurveda
from .health import get_health
from .spiritual_practices import get_spiritual_practices
from .talents import get_talents
from .profession import get_profession
from .finances import get_finances
from .love import get_love
from .family import get_family
from .compatibility import get_compatibility
from .forecast import get_forecast
